openapi: 3.0.0
info:
  title: apiForDocs
  version: '1.0'
  description: simple api description
  contact:
    url: 'https://stoplight.io/'
    name: Awesome Company
    email: qa@stoplight.io
  termsOfService: 'https://stoplight.io/terms/'
  license:
    name: Cool license
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: 'http://localhost:3000'
    description: greatServerName
  - description: anotherServerName
    url: 'http://localhost:4600'
paths: {}
components:
  schemas: {}
  securitySchemes:
    API Key - 1:
      name: API Key
      type: apiKey
      in: query
    API Key - 2:
      name: API Key
      type: apiKey
      in: query
    API Key - 3:
      name: API Key
      type: apiKey
      in: query
security:
  - API Key - 2: []
