openapi: 3.0.0
info:
  title: apiForDocs
  version: '1.0'
  description: simple api description
  contact:
    url: 'https://stoplight.io/'
    name: Awesome Company
    email: qa@stoplight.io
  termsOfService: 'https://stoplight.io/terms/'
  license:
    name: Cool license
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: 'http://localhost:3000'
    description: greatServerName
  - description: anotherServerName
    url: 'http://localhost:4600'
paths:
  /users:
    get:
      summary: get me some users
      tags: []
      responses:
        '200':
          description: OK
          headers:
            header-0:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseString:
                    type: string
      operationId: get-users
      description: getting users is awesome
      security:
        - API Key - 3: []
      parameters:
        - schema:
            type: string
          in: header
          name: get-users-header
          description: ''
        - schema:
            type: string
          in: query
          name: get-users-qp
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                stachursky:
                  type: string
                infinite:
                  type: number
    post:
      summary: add moar userz
      tags: []
      responses: {}
      operationId: post-users
components:
  schemas: {}
  securitySchemes:
    API Key - 1:
      name: API Key
      type: apiKey
      in: query
    API Key - 2:
      name: API Key
      type: apiKey
      in: query
    API Key - 3:
      name: API Key
      type: apiKey
      in: query
security:
  - API Key - 2: []
